# Generated by Django 5.2.13 on 2026-05-20 00:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='N/A', max_length=50)),
                ('model_name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('SEDAN', 'Sedan'), ('SUV', 'SUVs'), ('HATCHBACK', 'Hatchbacks'), ('STATION_WAGON', 'Station Wagons'), ('COUPE', 'Coupes'), ('CONVERTIBLE', 'Convertibles'), ('MOTORCYCLE', 'Motorcycles'), ('SCOOTER', 'Scooters & Minibikes'), ('TRUCK_4X4', 'Trucks & 4x4s'), ('VANS', 'Vans'), ('RV_CAMPER', 'RVs & Campers'), ('ELECTRIC_CAR', 'Electric Cars'), ('SUPERCAR', 'Supercars'), ('LUXURY', 'Luxury Cars'), ('CITY_CAR', 'City Cars'), ('HEAVY_TRUCK', 'Heavy Trucks'), ('CLASSIC_CAR', 'Classic Cars'), ('RIGHT_HAND_DRIVE', 'Right Hand Drive Cars'), ('SERVICE_VEHICLE', 'Service Vehicles'), ('HOT_ROD', 'Hot Rods'), ('CROSSOVER', 'Crossovers'), ('MUSCLE_CAR', 'Muscle Cars'), ('OFF_ROAD', 'Off-Roaders'), ('HYBRID_CAR', 'Hybrid Cars'), ('MINIVAN', 'Minivans'), ('BOAT', 'Boats'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=30)),
                ('year', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_negotiable', models.BooleanField(default=False)),
                ('image_url', models.URLField(max_length=500)),
                ('description', models.TextField(default='No description provided.')),
                ('engine', models.CharField(default='N/A', max_length=50)),
                ('horsepower', models.IntegerField(default=0)),
                ('drivetrain', models.CharField(default='FWD', max_length=10)),
                ('transmission', models.CharField(default='Manual', max_length=20)),
                ('torque', models.IntegerField(default=0)),
                ('consumption', models.CharField(default='0.0 l/100km', max_length=30)),
                ('mileage', models.IntegerField(default=0)),
                ('interior_color', models.CharField(default='Black', max_length=30)),
                ('exterior_color', models.CharField(default='White', max_length=30)),
                ('wheel_size', models.IntegerField(default=17)),
                ('doors', models.IntegerField(default=4)),
                ('passengers', models.IntegerField(default=5)),
                ('is_right_hand_drive', models.BooleanField(default=False)),
                ('location', models.CharField(default='Unknown', max_length=100)),
                ('seller_type', models.CharField(choices=[('PRIVATE', 'Private'), ('DEALER', 'Dealer'), ('UNKNOWN', 'Unknown')], default='PRIVATE', max_length=15)),
                ('video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.FloatField(default=5.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='vehicles.vehicle')),
            ],
        ),
    ]
