# Generated by Django 5.2.13 on 2026-05-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_review_id_alter_vehicle_consumption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(default='Gasoline', max_length=50),
        ),
    ]
