# Generated by Django 5.2.13 on 2026-06-07 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_remove_vehicle_image_url_vehicleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleimage',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/'),
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
